<script setup lang="ts">
import type { TransactionCategory } from '@/modules/transactions'
import type { AssetAccount } from '../api/asset.api'
import type { TransactionType } from '@/modules/transactions'
const props = defineProps<{ categories: TransactionCategory[]; accounts: AssetAccount[]; error?: string }>()
const emit = defineEmits<{ close: []; saved: [{ form: { type: TransactionType; amount: string; transaction_date: string; category_id: string; from_account_id: string; description: string } }] }>()
const form = defineModel<{ type: TransactionType; amount: string; transaction_date: string; category_id: string; from_account_id: string; description: string }>({ required: true })
</script>
<template><div class="fixed inset-0 z-50 grid place-items-center bg-slate-900/40 p-5" @click.self="emit('close')"><div class="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><div class="mb-5 flex justify-between"><h2 class="text-xl font-bold text-slate-800">Tambah transaksi</h2><button class="text-2xl text-slate-400" @click="emit('close')">×</button></div><div class="grid gap-3 sm:grid-cols-2"><select v-model="form.type" class="rounded-lg border p-2" @change="form.category_id = ''"><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select><input v-model="form.amount" type="number" placeholder="Nominal" class="rounded-lg border p-2"><input v-model="form.transaction_date" type="date" class="rounded-lg border p-2"><select v-model="form.from_account_id" class="rounded-lg border p-2"><option value="">Pilih akun aset</option><option v-for="account in props.accounts" :key="account.id" :value="account.id">{{ account.type }}{{ account.subtype ? ` · ${account.subtype}` : '' }} — Rp {{ new Intl.NumberFormat('id-ID').format(account.balance) }}</option></select><select v-model="form.category_id" class="rounded-lg border p-2 sm:col-span-2"><option value="">Pilih kategori</option><option v-for="category in props.categories.filter((item) => item.type === form.type)" :key="category.id" :value="category.id">{{ category.name }}</option></select><input v-model="form.description" placeholder="Deskripsi (opsional)" class="rounded-lg border p-2 sm:col-span-2"></div><p v-if="props.error" class="mt-3 text-sm text-red-600">{{ props.error }}</p><div class="mt-5 flex justify-end gap-2"><button class="rounded-lg border px-4 py-2" @click="emit('close')">Batal</button><button class="rounded-lg bg-brand-700 px-4 py-2 text-white" @click="emit('saved', { form })">Simpan</button></div></div></div></template>
